# Generated by Django 5.1.4 on 2025-01-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='category',
        ),
        migrations.CreateModel(
            name='NewCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newcategory')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.new')),
            ],
            options={
                'verbose_name_plural': 'Связи новостей с категориями',
                'unique_together': {('new', 'category')},
            },
        ),
        migrations.AddField(
            model_name='new',
            name='categories',
            field=models.ManyToManyField(through='news.NewCategoryAssignment', to='news.newcategory'),
        ),
    ]
