# Generated by Django 4.2 on 2024-12-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='main_photo',
        ),
    ]
