# Generated by Django 4.2 on 2024-12-10 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_new_main_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newcategory',
            options={'verbose_name_plural': 'Категории новостей'},
        ),
        migrations.AlterModelOptions(
            name='newphoto',
            options={'verbose_name_plural': 'Фото для новости'},
        ),
    ]
