# Generated by Django 4.2 on 2024-12-16 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_new_options_alter_newcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.newcategory'),
        ),
    ]
