# Generated by Django 4.2 on 2024-12-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_new_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newphoto',
            name='photo',
            field=models.ImageField(upload_to='news_photos/'),
        ),
    ]
