# Generated by Django 4.2 on 2024-12-20 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newphoto_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newphoto',
            name='photo',
        ),
        migrations.AddField(
            model_name='newphoto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newphoto',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='news_photos/'),
            preserve_default=False,
        ),
    ]
