# Generated by Django 5.1.4 on 2024-12-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_newphoto_photo_newphoto_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='news', to='news.newphoto'),
        ),
    ]
