# Generated by Django 4.2 on 2024-12-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_historicalauto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='file_path',
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
