# Generated by Django 4.2 on 2024-12-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_photo_file_name_remove_photo_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
